### ISSUE TITLE
Thanks! Level 2 tool linked below

### ISSUE THREAD

**Issue by rbavery** [and-viceversa/landsat_L1_qa_tool#1]
Thanks for posting this @and-viceversa . I adapted it to work with the pixel_qa band that is shipped with Level 2 surface reflectance: https://github.com/rbavery/landsat_L2_qa/blob/main/README.md

**Comment by and-viceversa** [comment]
@rbavery This repo was created during undergrad days... I dread looking at anything I wrote that long ago. Glad it's still of some use!
